default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("RDB_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("RDB_PASSWORD") { 'postgres' } %>
  host: <%= ENV.fetch("RDB_HOST") { 'localhost' } %> #if run docker pls fix to db
  port: <%= ENV.fetch("RDB_PORT") { 5432 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cap2-api_medicine
test:
  <<: *default
  database: cap2-api_medicine_test

production:
  <<: *default
  database: cap2-api_medicine_production
